sonar.projectKey=teilorbarcelos_auth-service-python
sonar.projectName=Auth Service Python
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://localhost:9000
# sonar.login is set via CI environment variable SONAR_TOKEN

sonar.exclusions=**/venv/**,**/migrations/**,**/storage/**,**/scripts/**,**/infra/**
